### ISSUE TITLE
Lunar Crashes After I Used The Tool

### ISSUE THREAD

**Issue by daffiazhar** [Whatlify/CrackedLunarAccountTool#1]
It always crashes after i launch the game using the tool

**Comment by daffiazhar** [comment]
UPDATE: I removed all accounts and, it broke my lunar. Fuck you.

**Comment by Whatlify** [comment]
That's your own issue. Make sure you provide details on the crash & what you entered when you created a new account using the tool. I can't just magically find out what the issue is with what you just said. You also have the code incase you ever want to debug it for yourself but I believe you broke it because of incorrect use.
